use_frameworks!

platform :ios, '8.0'

target 'JTBuriedPointLib_Example' do
  pod 'JTBuriedPointLib', :path => '../'

  target 'JTBuriedPointLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
